/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : usb-scanner-emulator
 #	author : miyako
 #	2016/03/02
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

#if VERSIONWIN
#include <vector>
#endif

void PluginMain(PA_long32 selector, PA_PluginParameters params)
{
	try
	{
		PA_long32 pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (PA_long32 pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{
// --- debug

		case 1 :
			POST_TEXT(pResult, pParams);
			break;

	}
}

// ------------------------------------- debug ------------------------------------

#if VERSIONMAC

// a key to press: the (layout-position based) virtual key code, and whether Shift is needed
struct MacKey
{
	CGKeyCode code;
	bool shift;
};

// returns false if the character has no mapping (it is then skipped, not typed)
static bool mac_key_for_char(UniChar c, MacKey &k)
{
	k.shift = false;
	
	// letters: upper case = same key + Shift
	if((c >= 'A') && (c <= 'Z'))
	{
		k.shift = true;
		c = (UniChar)(c + ('a' - 'A'));
	}
	
	switch (c)
	{
		// digits and arithmetic characters are sent as keypad keys (scanner-like)
		case '0': k.code = kVK_ANSI_Keypad0; return true;
		case '1': k.code = kVK_ANSI_Keypad1; return true;
		case '2': k.code = kVK_ANSI_Keypad2; return true;
		case '3': k.code = kVK_ANSI_Keypad3; return true;
		case '4': k.code = kVK_ANSI_Keypad4; return true;
		case '5': k.code = kVK_ANSI_Keypad5; return true;
		case '6': k.code = kVK_ANSI_Keypad6; return true;
		case '7': k.code = kVK_ANSI_Keypad7; return true;
		case '8': k.code = kVK_ANSI_Keypad8; return true;
		case '9': k.code = kVK_ANSI_Keypad9; return true;
			
		case '=': k.code = kVK_ANSI_KeypadEquals; return true;
		case '-': k.code = kVK_ANSI_KeypadMinus; return true;
		case '+': k.code = kVK_ANSI_KeypadPlus; return true;
		case '*': k.code = kVK_ANSI_KeypadMultiply; return true;
		case '\n': k.code = kVK_ANSI_KeypadEnter; return true;
			
		case '\r': k.code = kVK_Return; return true;
		case '\t': k.code = kVK_Tab; return true;
			
		case ' ': k.code = kVK_Space; return true;
			
		// Shift + main-row digit
		case ')': k.code = kVK_ANSI_0; k.shift = true; return true;
		case '(': k.code = kVK_ANSI_9; k.shift = true; return true;
		// Shift + semicolon key
		case ':': k.code = kVK_ANSI_Semicolon; k.shift = true; return true;
			
		case ';': k.code = kVK_ANSI_Semicolon; return true;
		case '\\': k.code = kVK_ANSI_Backslash; return true;
		case ',': k.code = kVK_ANSI_Comma; return true;
		case '/': k.code = kVK_ANSI_Slash; return true;
		case '.': k.code = kVK_ANSI_Period; return true;
			
		case 'a': k.code = kVK_ANSI_A; return true;
		case 'b': k.code = kVK_ANSI_B; return true;
		case 'c': k.code = kVK_ANSI_C; return true;
		case 'd': k.code = kVK_ANSI_D; return true;
		case 'e': k.code = kVK_ANSI_E; return true;
		case 'f': k.code = kVK_ANSI_F; return true;
		case 'g': k.code = kVK_ANSI_G; return true;
		case 'h': k.code = kVK_ANSI_H; return true;
		case 'i': k.code = kVK_ANSI_I; return true;
		case 'j': k.code = kVK_ANSI_J; return true;
		case 'k': k.code = kVK_ANSI_K; return true;
		case 'l': k.code = kVK_ANSI_L; return true;
		case 'm': k.code = kVK_ANSI_M; return true;
		case 'n': k.code = kVK_ANSI_N; return true;
		case 'o': k.code = kVK_ANSI_O; return true;
		case 'p': k.code = kVK_ANSI_P; return true;
		case 'q': k.code = kVK_ANSI_Q; return true;
		case 'r': k.code = kVK_ANSI_R; return true;
		case 's': k.code = kVK_ANSI_S; return true;
		case 't': k.code = kVK_ANSI_T; return true;
		case 'u': k.code = kVK_ANSI_U; return true;
		case 'v': k.code = kVK_ANSI_V; return true;
		case 'w': k.code = kVK_ANSI_W; return true;
		case 'x': k.code = kVK_ANSI_X; return true;
		case 'y': k.code = kVK_ANSI_Y; return true;
		case 'z': k.code = kVK_ANSI_Z; return true;
			
		default:
			return false;
	}
}

// CGEventCreateKeyboardEvent can return NULL; never post or release a NULL event
static bool mac_post_key(CGEventSourceRef source, CGKeyCode code, bool down, bool shift)
{
	CGEventRef e = CGEventCreateKeyboardEvent(source, code, down);
	if(!e)
		return false;
	
	if(shift)
		CGEventSetFlags(e, kCGEventFlagMaskShift);
	
	CGEventPost(kCGHIDEventTap, e);
	CFRelease(e);
	return true;
}

#else

// append one keyboard event to the queue
static void win_push_key(std::vector<INPUT> &queue, WORD vk, bool up)
{
	INPUT e;
	ZeroMemory(&e, sizeof(e));
	e.type = INPUT_KEYBOARD;
	e.ki.wVk = vk;
	if(up)
		e.ki.dwFlags = KEYEVENTF_KEYUP;
	queue.push_back(e);
}

// send the queued events in one call; returns false if Windows did not accept all of them
// (e.g. blocked by UIPI when the foreground window is elevated)
static bool win_flush_keys(std::vector<INPUT> &queue)
{
	bool ok = true;
	if(!queue.empty())
	{
		UINT n = (UINT)queue.size();
		ok = (SendInput(n, &queue[0], sizeof(INPUT)) == n);
		queue.clear();
	}
	return ok;
}

// returns false if the character has no mapping on the current keyboard layout (it is then skipped)
static bool win_key_for_char(PA_Unichar c, WORD &vk, BYTE &mods)
{
	mods = 0;
	
	switch (c)
	{
		case '\r':
		case '\n':
			vk = VK_RETURN;
			return true;
		case '\t':
			vk = VK_TAB;
			return true;
	}
	
	// low byte: virtual key; high byte: bit 1 = Shift, bit 2 = Ctrl, bit 4 = Alt; -1 = no mapping
	SHORT r = VkKeyScanW((WCHAR)c);
	if(r == -1)
		return false;
	
	vk = (WORD)LOBYTE(r);
	mods = HIBYTE(r);
	return true;
}

#endif

void POST_TEXT(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_TEXT Param1;

	Param1.fromParamAtIndex(pParams, 1);

	CUTF16String t;
	Param1.copyUTF16String(&t);
	
#if VERSIONMAC
	// may be NULL; a NULL source is accepted by CGEventCreateKeyboardEvent (default source)
	CGEventSourceRef eventSource = CGEventSourceCreate(kCGEventSourceStateHIDSystemState);
	
	for(size_t i = 0; i < t.length(); ++i)
	{
		MacKey k;
		
		if(!mac_key_for_char((UniChar)t[i], k))
			continue;
		
		if(!mac_post_key(eventSource, k.code, true, k.shift))
			break;
		
		if(!mac_post_key(eventSource, k.code, false, k.shift))
			break;
	}
	
	if(eventSource)
		CFRelease(eventSource);
#else
	std::vector<INPUT> queue;
	queue.reserve(64);
	
	for(size_t i = 0; i < t.length(); ++i)
	{
		WORD vk;
		BYTE mods;
		
		if(!win_key_for_char(t[i], vk, mods))
			continue;
		
		if(mods & 1) win_push_key(queue, VK_SHIFT, false);
		if(mods & 2) win_push_key(queue, VK_CONTROL, false);
		if(mods & 4) win_push_key(queue, VK_MENU, false);
		
		win_push_key(queue, vk, false);
		win_push_key(queue, vk, true);
		
		if(mods & 4) win_push_key(queue, VK_MENU, true);
		if(mods & 2) win_push_key(queue, VK_CONTROL, true);
		if(mods & 1) win_push_key(queue, VK_SHIFT, true);
		
		// flush in chunks so the queue stays small; each call is accepted or refused as a whole
		if(queue.size() >= 128)
		{
			if(!win_flush_keys(queue))
				return;
		}
	}
	
	win_flush_keys(queue);
#endif
	
}
