/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : usb-scanner-emulator
 #	author : miyako
 #	2016/03/02
 #
 # --------------------------------------------------------------------------------*/



// --- debug
void POST_TEXT(sLONG_PTR *pResult, PackagePtr pParams);
